### ISSUE TITLE
DH paramters

### ISSUE THREAD

**Issue by elgamal20201** [Evrid/Portrait-Drawing-with-Robot-arm-Coordinate-Conversion-using-Computer-Vision#1]
how can i use it on my robot i was need it as XYZ to inter it in inverse kinematics
also i tryed to discovered where i can edit to my dh paramter i cant found can you help me 
also if there are and contact such as discord please tell me

**Comment by Evrid** [comment]
you get the parameter then change the code in MATLAB to get a different calculation result
